feat(TD-23): Make UI responsive and validate task input
taiman-siddiqui-sazim/to-do-app pull request #7
Opened 2024-12-11 19:34 UTC by taiman-siddiqui-sazim

**Description of change**

- UI components are responsive to different device resolutions
- Long tasks get truncated and can be expanded
- Zod form validates input before adding or editing tasks
- Popup displays if a task has been added

**Associated Trello link**

https://trello.com/c/9CASKi9o

**Screenshot of changes**

**1) Responsive UI**

![Screenshot 2024-12-12 at 1 19 39 AM](https://github.com/user-attachments/assets/6203fcf5-d498-4e21-89f2-f3ae8469a82c)

**2) Long task management**

![Screenshot 2024-12-12 at 1 21 53 AM](https://github.com/user-attachments/assets/f3f9936a-1c09-4830-8fcf-740024263597)

![Screenshot 2024-12-12 at 1 22 26 AM](https://github.com/user-attachments/assets/712a9588-4a79-4186-afeb-bbb9c5f5fe94)

**3) Zod validation**

![Screenshot 2024-12-12 at 1 24 40 AM](https://github.com/user-attachments/assets/24450899-59e7-4ea4-b86a-ae4e756dc945)

**Dev notes**

Addresses following changes requested in Frontend:

1) Removes HTML default rendering, which trims spaces between characters
2) Manages text overflow
3) Makes UI components responsive
4) Validates input to add and edit tasks
5) Notifies user that task has been added with popup

2024-12-11 22:30 UTC, nur-zaman-sazim requested changes
NIT: Add a line break at the end of the files where there isn't one.

2024-12-11 22:30 UTC, nur-zaman-sazim commented on modules/to-do/components/AddTask/AddTask.tsx
> +          {/* Display error message above the input */}
please remove comments

2024-12-11 23:44 UTC, ishmamur-rahman-sazim requested changes

2024-12-11 23:44 UTC, ishmamur-rahman-sazim commented on shared/typedefs/helpers.ts
> +export const HTaskSchema = z.object({
The convention is just for Enums, Types and Interfaces. This can be `taskFormSchema` or `taskSchema`.

2024-12-11 23:44 UTC, ishmamur-rahman-sazim commented on modules/to-do/components/DeleteTask/DeleteTask.tsx
> +  if (!isOpen) return null;
[JC] Does the component still render if we remove this line?

2024-12-11 23:44 UTC, ishmamur-rahman-sazim commented on modules/to-do/components/TaskList/TaskList.tsx
> +              ? `${task.title.slice(0, 40)}...`
Let's create a shared `constants.ts` file and define `MAX_TITLE_LENGTH` there. This would make it reusable, and we can do `title.slice(0, MAX_TITLE_LENGTH)`.

[Read up on magic values](https://kyleshevlin.com/what-are-magic-values/)

2024-12-12 09:47 UTC, taiman-siddiqui-sazim commented on modules/to-do/components/DeleteTask/DeleteTask.tsx
> +  if (!isOpen) return null;
Yes it will render, as the _isOpen_ param passed to the Delete component contains a task and is therefore true. This is just a sanity check to make sure a task is being passed to the component.

2024-12-12 11:02 UTC, merged