feat(TD-8): Add and fetch tasks from backend
taiman-siddiqui-sazim/to-do-app pull request #8
Opened 2024-12-18 23:12 UTC by taiman-siddiqui-sazim

**Description of change**

- User can add a task to the backend
- Added task/s get fetched from the backend

**Associated Trello link**

https://trello.com/c/c4vCZIbG

**Screenshot of change**

- Add the following task to the backend: 
<img width="756" alt="Screenshot 2024-12-19 at 6 08 24 AM" src="https://github.com/user-attachments/assets/3e333334-08f8-46c8-b291-93d4a64db8f6" />
- Added task is fetched from the backend:
<img width="755" alt="Screenshot 2024-12-19 at 6 10 45 AM" src="https://github.com/user-attachments/assets/95099e80-bfc0-4057-ade8-ab4b8f234a7d" />

**Dev notes** 

Features to edit, delete and mark completion of tasks has not been implemented yet.

2024-12-22 01:02 UTC, nur-zaman-sazim commented on modules/to-do/components/AddTask/AddTask.tsx
> +      setTimeout(() => setShowPopup(false), 2000);
ooc: why are we using timeout here ?

2024-12-24 16:09 UTC, mahir-mohsin-sazim requested changes

2024-12-24 16:09 UTC, mahir-mohsin-sazim commented on shared/utils/TaskApi.ts
> +      const url = taskId ? `${API_BASE_URL}/${taskId}` : API_BASE_URL; // Conditional endpoint
Remove comments

2024-12-24 16:09 UTC, mahir-mohsin-sazim commented on shared/typedefs/constants.ts
> +export const API_BASE_URL = "http://localhost:3001/api/v1/tasks";
Shouldn't this be in `.env` file??

2024-12-24 16:09 UTC, mahir-mohsin-sazim commented on modules/to-do/containers/ToDoPageContainer.tsx
> +      console.error("Error fetching added task:", error);
Just a quick reminder, for the next project you need to do proper error handling. `console.loging` the error won't be acceptable.

2024-12-26 09:10 UTC, taiman-siddiqui-sazim commented on modules/to-do/components/AddTask/AddTask.tsx
> +      setTimeout(() => setShowPopup(false), 2000);
To display the popup after adding task for 2 seconds.

2024-12-26 14:09 UTC, merged